---
version: '3'

tasks:
  proto:generate:
    vars:

    cmds:
      - protoc --go_out=. --go_opt=module=github.com/fuhrmannb/grpc_multiplexer --go-grpc_out=. --go-grpc_opt=module=github.com/fuhrmannb/grpc_multiplexer protobuf/grpc/multiplexer/*.proto
    silent: true
