// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protobuf/grpc/multiplexer/discovery.proto

package discovery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiscoveryClient is the client API for Discovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryClient interface {
	ListGRPCServer(ctx context.Context, in *ListGRPCServerRequest, opts ...grpc.CallOption) (*ListGRPCServerResponse, error)
	WatchGRPCServer(ctx context.Context, in *WatchGRPCServerRequest, opts ...grpc.CallOption) (Discovery_WatchGRPCServerClient, error)
}

type discoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryClient(cc grpc.ClientConnInterface) DiscoveryClient {
	return &discoveryClient{cc}
}

func (c *discoveryClient) ListGRPCServer(ctx context.Context, in *ListGRPCServerRequest, opts ...grpc.CallOption) (*ListGRPCServerResponse, error) {
	out := new(ListGRPCServerResponse)
	err := c.cc.Invoke(ctx, "/grpc.multiplexer.Discovery/ListGRPCServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) WatchGRPCServer(ctx context.Context, in *WatchGRPCServerRequest, opts ...grpc.CallOption) (Discovery_WatchGRPCServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &Discovery_ServiceDesc.Streams[0], "/grpc.multiplexer.Discovery/WatchGRPCServer", opts...)
	if err != nil {
		return nil, err
	}
	x := &discoveryWatchGRPCServerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Discovery_WatchGRPCServerClient interface {
	Recv() (*WatchGRPCServerResponse, error)
	grpc.ClientStream
}

type discoveryWatchGRPCServerClient struct {
	grpc.ClientStream
}

func (x *discoveryWatchGRPCServerClient) Recv() (*WatchGRPCServerResponse, error) {
	m := new(WatchGRPCServerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DiscoveryServer is the server API for Discovery service.
// All implementations must embed UnimplementedDiscoveryServer
// for forward compatibility
type DiscoveryServer interface {
	ListGRPCServer(context.Context, *ListGRPCServerRequest) (*ListGRPCServerResponse, error)
	WatchGRPCServer(*WatchGRPCServerRequest, Discovery_WatchGRPCServerServer) error
	mustEmbedUnimplementedDiscoveryServer()
}

// UnimplementedDiscoveryServer must be embedded to have forward compatible implementations.
type UnimplementedDiscoveryServer struct {
}

func (UnimplementedDiscoveryServer) ListGRPCServer(context.Context, *ListGRPCServerRequest) (*ListGRPCServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGRPCServer not implemented")
}
func (UnimplementedDiscoveryServer) WatchGRPCServer(*WatchGRPCServerRequest, Discovery_WatchGRPCServerServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchGRPCServer not implemented")
}
func (UnimplementedDiscoveryServer) mustEmbedUnimplementedDiscoveryServer() {}

// UnsafeDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServer will
// result in compilation errors.
type UnsafeDiscoveryServer interface {
	mustEmbedUnimplementedDiscoveryServer()
}

func RegisterDiscoveryServer(s grpc.ServiceRegistrar, srv DiscoveryServer) {
	s.RegisterService(&Discovery_ServiceDesc, srv)
}

func _Discovery_ListGRPCServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGRPCServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).ListGRPCServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.multiplexer.Discovery/ListGRPCServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).ListGRPCServer(ctx, req.(*ListGRPCServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Discovery_WatchGRPCServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchGRPCServerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscoveryServer).WatchGRPCServer(m, &discoveryWatchGRPCServerServer{stream})
}

type Discovery_WatchGRPCServerServer interface {
	Send(*WatchGRPCServerResponse) error
	grpc.ServerStream
}

type discoveryWatchGRPCServerServer struct {
	grpc.ServerStream
}

func (x *discoveryWatchGRPCServerServer) Send(m *WatchGRPCServerResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Discovery_ServiceDesc is the grpc.ServiceDesc for Discovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Discovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.multiplexer.Discovery",
	HandlerType: (*DiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGRPCServer",
			Handler:    _Discovery_ListGRPCServer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchGRPCServer",
			Handler:       _Discovery_WatchGRPCServer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/grpc/multiplexer/discovery.proto",
}
